version: "3.9"

services:
  ipsec-1:
    image: energy1190/openswan
    networks:
      ipsec-net:
        ipv4_address: 10.5.1.1
    hostname: ipsec-1
    volumes:
      - ./ipsec-1.conf:/etc/ipsec.conf

  ipsec-2:
    image: energy1190/openswan
    networks:
      ipsec-net:
        ipv4_address: 10.5.2.1
    hostname: ipsec-2
    volumes:
      - ./ipsec-2.conf:/etc/ipsec.conf

networks:
  ipsec-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
