version: "3.9"

services:
  server1:
    image: ubuntu
    networks:
      net1:
        ipv4_address: 10.5.1.2
    hostname: server1
    command:
      - sleep
      - infinity

  server2:
    image: ubuntu
    networks:
      net2:
        ipv4_address: 10.5.2.2
    hostname: server2
    command:
      - sleep
      - infinity

  ipsec1:
    # build: ./openswan
    image: hwdsl2/ipsec-vpn-server
    networks:
      ipsec:
        ipv4_address: 10.5.3.2
      net1:
        ipv4_address: 10.5.1.3
    privileged: true
    hostname: ipsec1
    volumes:
      - ./ipsec1.conf:/etc/ipsec.d/vpn.conf:ro
      # - ./vpn.secrets:/etc/ipsec.d/vpn.secrets:ro
    environment:
      - VPN_IPSEC_PSK
      - VPN_USER
      - VPN_PASSWORD

  ipsec2:
    # build: ./openswan
    image: hwdsl2/ipsec-vpn-server
    networks:
      ipsec:
        ipv4_address: 10.5.3.3
      net2:
        ipv4_address: 10.5.2.3
    privileged: true
    hostname: ipsec2
    volumes:
      - ./ipsec2.conf:/etc/ipsec.d/vpn.conf:ro
      # - ./vpn.secrets:/etc/ipsec.d/vpn.secrets:ro
    environment:
      - VPN_IPSEC_PSK
      - VPN_USER
      - VPN_PASSWORD

networks:
  net1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.1.0/24
          gateway: 10.5.1.1

  net2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.2.0/24
          gateway: 10.5.2.1

  ipsec:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.3.0/24
          gateway: 10.5.3.1
